### ISSUE TITLE
checkmk newbie

### ISSUE THREAD

**Issue by sync2019** [WojRep/Check_MK-ZTE-OLT-C3xx-ONU#2]
pls can you give some tutor coz i have a problem to connect the olt c300 v2.1 via snmp. mkcheck null. can you give me step by step instruction sir?

**Comment by WojRep** [comment]
You need to configure the snmp section settings on the C300 device, set access, enable, set up communities and views.
This is well documented in the ZTE documentation.


Configuration example C300:
```
acl standard name ACL_SNMP
  rule 1 permit 192.168.100.20 0.0.0.0
  rule 2 permit 192.168.10.0 0.0.0.255
!
snmp-server location SSSSSSSS UUUUUUU 0000000
snmp-server contact DONALD MIKEY PHONE +1 xxxx xxxxx xxxxx
snmp-server access-list ACL_SNMP
snmp-server community YOUR_COMMUNITY view Allview rw
snmp-server view AllView 1.2 included 
snmp-server view AllView 1.3 included 
```

In CheckMK you add a host (C300) and set it to communicate with snmp using YOUR_COMMUNITY version of the v2c protocol.

Then (if you haven't done it before) you upload and install this plugin to CheckMK: zte_c3xx_onu-2.0.mkp

It all requires you to be familiar with the operation of CheckMK. There are very good manuals and videos on the website of the manufacturer CheckMK.

If this was not helpful, you need to write in more detail, indicate your configuration, screenshots, describe the network.

**Comment by sync2019** [comment]
![IMG-20220810-WA0010](https://user-images.githubusercontent.com/110918924/183834935-54e6802e-3bab-4160-83bf-0d3086a90c90.jpg)
![IMG-20220810-WA0011](https://user-images.githubusercontent.com/110918924/183835005-9e39601b-87ac-47f2-a531-d9f191884278.jpg)
![IMG-20220810-WA0008](https://user-images.githubusercontent.com/110918924/183835008-3b7f8c64-b02d-4e9b-9c10-92395f5563a6.jpg)
![IMG-20220810-WA0009](https://user-images.githubusercontent.com/110918924/183835010-6d98fb3d-f0d7-463f-83d1-51087784d69b.jpg)
olt ip:192.168.92.100
pc : 192.168.92.2
checkmk using docker container.

**Comment by WojRep** [comment]
Let's start with some changes and information:
1) Change this setting in the host parameters in CheckMK.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/NnYkF45/2022-08-10-09-02-1.png" alt="2022-08-10-09-02-1" border="0"></a>
to "Configured API integrations, no Checkmk agent"

2) Do you have "public1" entered here?
<a href="https://imgbb.com/"><img src="https://i.ibb.co/6PJPmtF/2022-08-10-09-02.png" alt="2022-08-10-09-02" border="0"></a>

3) Perform a test after the changes
<a href="https://imgbb.com/"><img src="https://i.ibb.co/g6YHhZc/2022-08-10-09-18.png" alt="2022-08-10-09-18" border="0"></a>

**Comment by sync2019** [comment]
fail, i got snmp error on ZXAN: snmp query timed out after 6 tries within 6.01 second

**Comment by sync2019** [comment]
![Screen Shot 2022-08-10 at 14 58 50](https://user-images.githubusercontent.com/110918924/183847485-c1bb5430-d839-4f7b-8874-64e5401ba007.png)
![Screen Shot 2022-08-10 at 14 56 24](https://user-images.githubusercontent.com/110918924/183847540-972f0b7d-abcf-47b3-94d7-9dd460b023dd.png)

**Comment by WojRep** [comment]
1) Show acl ACL_SNMP (OLT config)
2) You don't show all the information in the screenshots. Please don't cut it.
3) Can CheckMK ping the OLT? (from docker CLI shell)

**Comment by sync2019** [comment]
![Screen Shot 2022-08-10 at 16 22 05](https://user-images.githubusercontent.com/110918924/183866272-1d91fa7a-1ee6-4638-8e01-ae88e8c40393.png)
![Screen Shot 2022-08-10 at 16 25 03](https://user-images.githubusercontent.com/110918924/183866329-78709dc6-a190-4fef-80ff-0ccd8fde4af6.png)

**Comment by sync2019** [comment]
i use both my connection, 172 is my wireless ip and 192.168.92.0 is direct access to mng olt via cable. both of them are fail. i can run snmpwalk on my mikrotik and get request but fail to run on my OLT.

**Comment by sync2019** [comment]
![Screen Shot 2022-08-10 at 16 34 30](https://user-images.githubusercontent.com/110918924/183868489-43f05e16-eb0f-4f0c-8549-55d599b2b20b.png)

**Comment by WojRep** [comment]
<a href="https://ibb.co/WsS6Yyj"><img src="https://i.ibb.co/vD2HKPR/2022-08-10-11-47.png" alt="2022-08-10-11-47" border="0"></a>

**Comment by sync2019** [comment]
![Screen Shot 2022-08-10 at 17 53 47](https://user-images.githubusercontent.com/110918924/183884814-55391349-810a-4507-be4a-8df47af31942.png)
![Screen Shot 2022-08-10 at 17 55 28](https://user-images.githubusercontent.com/110918924/183884825-734ba16b-6341-420e-aaa1-87f5d4df0c78.png)
great, snmp is work well, then how i see the status of my onu tx/rx power like yours sir

**Comment by sync2019** [comment]
![Screen Shot 2022-08-10 at 17 58 17](https://user-images.githubusercontent.com/110918924/183885159-1fa6e9eb-c014-4cc8-95c5-a51d6899892a.png)

**Comment by sync2019** [comment]
![Screen Shot 2022-08-10 at 18 05 03](https://user-images.githubusercontent.com/110918924/183886249-bbff7154-b7dd-46eb-8467-58f0500ff312.png)
done thank you very much for your help sir
