### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by ari123mster** [WojRep/Check_MK-ZTE-OLT-C3xx-ONU#3]
how to install sir?
sorry im newbie

**Comment by WojRep** [comment]
Hello, 

Full instructions: [https://docs.checkmk.com/latest/en/](https://docs.checkmk.com/latest/en/)

**Comment by ari123mster** [comment]
ohh sorry bad question
i ask how to configure this package on my olt c320
there is a tutorial?
